name: ohw20-proj-shiptrack
channels:
  - conda-forge
dependencies:
  - python=3.8
  - bokeh
  - bottleneck
  - cartopy <0.18
  # - cf-units
  # - cf_xarray
  - colorcet
  # - compilers
  # - ctd
  - dask
  - datashader
  - descartes
  - erddapy
  - geopandas
  - geoviews
  - gsw
  - h5netcdf
  - holoviews
  - hvplot
  # - intake
  # - ioos-tools
  - ipyleaflet
  # - jupyter
  # - jupyter_contrib_nbextensions
  # - jupyterlab
  - matplotlib-base
  - nc-time-axis
  - netcdf4
  - numpy
  - palettable
  - pandas<1.1
  # movingpandas does not install properly if panel is not included
  - panel
  - param
  - rasterio
  - requests
  - retrying
  - s3fs
  - scipy
  - seaborn
  - shapely
  - xarray
  - xlrd
  - zarr
  # ohw20-proj-shiptrack
  - nb_conda_kernels
  - geojson
  # If movingpandas is unpinned, 0.2rc1 is installed.
  # With movingpandas==0.3rc1, the run-time version label says 0.2.rc2, not 0.3!
  - movingpandas==0.3rc1
  